apartmentsapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AppListView.as_view(), name="home"),
]

jasnaproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apartmentsapp.urls"), name="AppListView"),
    path('summernote/', include('django_summernote.urls')),
]

apartmentsapp/models.py
import datetime
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
import uuid 
# import cloudinary.uploader
# from django.db.models.signals import pre_delete
# import cloudinary

STATUS = ((0, "Available"), (1, "Occupied"), (2, "Pending"))


class Photo(models.Model):
    """ An image object to be uploaded """
    image = CloudinaryField('image')
    photo_id = models.CharField(max_length=7, unique=True)
    caption = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return self.caption if self.caption != "" else "No caption"
    
class Gallery(models.Model):
    """ Creating a Gallery for the apartments """
    photos = models.ManyToManyField('Photo', blank=True)

# class AppName(models.Model):
#     """ Using name to distinguish between apartments """
#     name = models.CharField(max_length=15, unique=True, blank=False)

#     def __str__(self):
#         return f'{self.name}'

class Apartment(models.Model):
    """ Main model of an apartment object """
    APP_NAMES = (('TONY', 'tony'), ('MATEA', 'matea'), ('MARTINA', 'martina'))
    name = models.CharField(max_length=10, choices=APP_NAMES)
    slug = models.SlugField(max_length=200, unique=True)
    bedroom_nr = models.IntegerField()
    sofa_bed = models.BooleanField(default=True)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='post_app')
    upload_image = CloudinaryField('image')
    more_images = CloudinaryField('another_image')
    last_update = models.DateField(auto_now=True)
    description = models.TextField(max_length=3000)
    
    def __str__(self):
        return f'{self.owner} has uploaded an offer of {self.name} apartment with {self.bedroom_nr} for the {self.price} price. '


class Booking(models.Model):
    """ An object to be accepted or denied by the owner """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    booking_id = models.UUIDField(default=uuid.uuid4, editable=False, max_length=8)
    status = models.IntegerField(choices=STATUS, default=0)
    check_in = models.DateField()
    check_out = models.DateField()
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f'From = {self.check_in.strftime("%d-%b-%Y %H:%M")} To = {self.check_out.strftime("%d-%b-%Y %H:%M")}'



def check_availability(apartment, check_in, check_out):
    """ A function to check availability """
    avail_list = []
    booking_list = Booking.objects.filter(apartment=apartment)
    for booking in booking_list:
        if booking.check_in > check_out or booking.check_out < check_in:
            avail_list.append(True)
        else:
            avail_list.append(False)
    return all(avail_list)

class Person(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

apartmentsapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import  Photo, Gallery

class ImageForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields=['multipleimages']  
        label ={}
        widgets ={
            'multipleimages':forms.FileInput(attrs={'id':'myfile','class':'form-control-file','multiple':True}),
        } 

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'caption')

apartmentsapp/views.py
# from django.shortcuts import render, HttpResponse, redirect
# from django.views.generic import ListView
import datetime
from django.views.generic import ListView
from .models import Apartment


class AppListView(ListView):
    """ The landing page with offer of the apartments """
    model = Apartment
    template_name = 'index.html'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['last_update'] = datetime.datetime.now()
        return context

    









# from .forms import PhotoForm
# from .models import Photo

# def add_photo(request):
#     """ A function to upload images """
#     if request.method == "POST":
#         form = PhotoForm(request.POST, request.FILES)
#         if form.is_valid():
#             photo = Photo()
#             photo.caption = request.POST.get('caption')
#             photo.save()
#             return redirect('/photo/' + photo.id)
#     else:
#         form = PhotoForm()

#     return render(request, 'add-photo.html', {'form': form})

templates/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Oswald:wght@285;300&family=Playfair+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/style.css">
    <title>Apartments Grganic</title>
</head>
<style>
    body {
        background: linear-gradient(90deg, rgb(14, 12, 49) 0%, rgb(24, 24, 124) 35%, rgba(0, 212, 255, 1) 100%);
    }
</style>


<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <div class="fixed-top">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4">
                <h5 class="text-white h4">Apartments Grganic</h5>
                <span class="text-muted">Welcome to Our Home</span>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if owner.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
    </div>
    <div>

        <img src="media/images/312107267.jpg">
    </div>

    <br>
    <br>
    <br>
    <br>



    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="card mb-3">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

</body>

</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}
{% csrf_token %}
<div class="container-fluid">
    <div class="row">
        Apartments
        <!-- Apartment Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for apartment in apartment_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if not apartment.upload_image.url %}
                                <img class="card-img-top" src="https://cf.bstatic.com/xdata/images/hotel/max1024x768/269536558.jpg?k=24be4ce4e6f46c606af0f3b992ac305b369f3923309b16349428172e17646265&o=&hp=1">
                                {% else %}
                                <img class="card-img-top" src=" {{ apartment.upload_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ apartment.owner }}</p>
                                </div>
                            </div>
                            <a href="#" class="post-link">
                                <h2 class="card-title">{{ apartment.name }}</h2>
                                <p class="card-text">{{ apartment.bedroom_nr }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ apartment.last_update }} <i class="far fa-heart"></i>
                                {{ apartment.price }} Euros</p>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}